server:
  port: 18801   #端口号
  tomcat:
    max-threads: 200
    min-spare-threads: 10


spring:
  profiles:
    active:
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false                            # 是否开启缓存默认为true
    prefix: classpath:/templates/           #设置thymeleaf路径默认为src/main/resources/templates
    suffix: .html                           # 设置thymeleaf模板后缀
    content-type: text/html
    mode: LEGACYHTML5                       # 设置thymeleaf严格校验
    encoding: UTF-8                         # 设置编码

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  task:
    scheduling:
      pool:
        size: 2